### ISSUE TITLE
Come mai non usi __main__ ?

### ISSUE THREAD

**Issue by Allan-Nava** [EthanITA/projecteuler#1]
A Basic Python main()
In some Python scripts, you may see a function definition and a conditional statement that looks like the example below:

```
def main():
    print("Hello World!")

if __name__ == "__main__":
    main()
```

**Comment by EthanITA** [comment]
All'inizio non mi sembrava necessario, ora a pensarci si potrebbe rivelare utile quando faccio gli import. Lo aggiornero, grazie :)

**Comment by Allan-Nava** [comment]
> All'inizio non mi sembrava necessario, ora a pensarci si potrebbe rivelare utile quando faccio gli import. Lo aggiornero, grazie :)

Nulla :)
